#!/bin/bash

IFS=$'\n'

verbose=0
depfile=.deps.db
depdirs=.deps*
move=1
vam_dir="/cygdrive/c/games/VaM/AddonPackages"
cd $vam_dir

pr_msg()
{
	[ $verbose -eq 1 ] && echo $*
}

pr_quiet()
{
	[ $verbose -eq 0 ] && echo $*
}

if [ ! -f $depfile ]
then
	echo "Preparing dependency cache..."
	var_list=$(find . -name "*.var")
	for var_path in $var_list
	do
		var=$(basename $var_path)
		deps=$(unzip -p "$var_path" meta.json | sed -rn "s|.*\"(.*)\.(.*)\.(.*)\".*:.*\{.*|\1.\2.\3|p")
		for dep in $deps
		do
			echo "$var:$dep" >> $depfile
		done
	done
else
	echo "Using existing '$vam_dir/$depfile'"
fi

 [ $move -eq 1 ] && echo "All unused packages will be moved to '$vam_dir'"

echo "Looking for unused packages..."
pkg_list=$(find $depdirs -name "*.var" | rev | cut -f 3- -d '.' | rev | sort -f | uniq)
for pkg_path in $pkg_list
do
	pkg=$(basename $pkg_path)
	pkg_tmpl="$(printf "%q" $pkg).*.var"
	vers=($(find $depdirs -name "$pkg_tmpl" | rev | cut -f 2- -d '.' | rev))
	latest=${vers[-1]}

	for ver_path in ${vers[*]}
	do
		ver=$(basename $ver_path)
		pr_msg "$ver_path.var"

		# check pkg.[0-9]
		deps=$(grep -F ":$ver" $depfile)
		# check pkg.latest
		[ $ver_path == $latest ] && deps="${deps:+$deps }$(grep -F ":$pkg.latest" $depfile)"


		if [ -z "$deps" ]
		then
			pr_msg "  UNUSED"
			pr_quiet "$ver_path"
			[ $move -eq 1 ] && mv "$ver_path.var" "$vam_dir"
		fi
		for dep in $deps
		do
			pr_msg "  $dep" | cut -f 1 -d ":"
		done
	done
done
